### ISSUE TITLE
No Licence provided

### ISSUE THREAD

**Issue by idiotwithalaptop** [realestate-com-au/intro-to-docker#12]
There has been no licence provided for this presentation/workshop.  Now since this is on REA's public Github, my assumption would be that it is intended for use by the wider open-source community.

Unfortunately, according to https://choosealicense.com/no-permission/, we do not have that privilage legally speaking.  Is this intended?  If not, can an appropriate licence please be added.

**Comment by mdub** [comment]
Apologies for the lack of license. 

As the originator of the first version of this material, it was certainly my intention that it would be open for community use and adaption. I think a [Creative Commons "Attribution" license](https://creativecommons.org/licenses/by/4.0/), or similar, would be suitable.

Hopefully those still at REA (hi @mbelekar, @yeungda-rea, @tvars) will agree.

**Comment by lukeck** [comment]
Thanks for raising this @idiotwithalaptop. It's an oversight on our part.

I agree with @mdub that a Creative Commons Attribution license seems reasonable for this. Our current internal guideline is to prefer the MIT license for opensource projects. That is totally reasonable for projects that are mostly code but may not be the best choice for training material such as this. Please bear with me a little longer while we work through this with our internal legal team.

**Comment by idiotwithalaptop** [comment]
Hi @lukeck , has there been any update on this??

**Comment by lukeck** [comment]
Sorry for the delay Ryan. Does this [license file](https://github.com/realestate-com-au/intro-to-docker/blob/gh-pages/LICENSE.md) resolve the issue?

**Comment by idiotwithalaptop** [comment]
It does!!!  Thanks Luke!!
