### ISSUE TITLE
Hi Mike,  I have just found that `REAMDE` does not match with `setup.sh` on checking version

### ISSUE THREAD

**Issue by hanmoi-choi** [realestate-com-au/intro-to-docker#3]
Hi Mike,

I have just found that `REAMDE` does not match with `setup.sh` with checking version

README

```
YAY: docker version 1.12.0
YAY: docker-compose version 1.8.0
```

Code

```
check_version docker 1.11.0
check_version docker-compose 1.7.0
```

**Comment by mdub** [comment]
Thanks. Yeah, that's intentional - the setup script will ensure that you have _at least_ 1.11 & 1.7 installed, but outputs the versions that are actually installed.
